FROM python:3.13-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

RUN apt-get update -y && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/requirements.txt

RUN pip install --upgrade pip setuptools wheel \
 && pip install python-oracledb \
 && pip install -r /app/requirements.txt

COPY . /app

EXPOSE ${PORT:-8000}

CMD uvicorn src.api:app --host 0.0.0.0 --port ${PORT:-8000}
